steps:
  - name: gcr.io/k8s-skaffold/skaffold
    args:
      - skaffold
      - build
      - '--interactive=false'
      - '--default-repo=us-central1-docker.pkg.dev/silicon-parity-339317/web-app'
      - '--file-output=artifacts.json'
    dir: example
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: 
      - '-c'
      - >
        gcloud deploy releases create web-app-$date-$time
        --delivery-pipeline=data-flow --build-artifacts=artifacts.json
        --source=./
        --region=us-central1
    dir: example
    entrypoint: bash 
