apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
#project: silicon-parity-339317
  cluster: projects/silicon-parity-339317/locations/us-central1-c/clusters/staging
